# matrix:
#   language: java
#   os:
#     - windows-latest
#     - ubuntu-latest

name: placeholder_Name

on:
  pull_request:
  push:
    branches:
      - branch-1

jobs:
  build:
    strategy:
      matrix:
        java: 
          - '8'
        os:
          - ubuntu-latest
          - windows-latest  
      fail-fast: FALSE
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java}}
          

    #     dependencies-cache-enabled: FALSE
    #   uses: actions/setup-java@version
    #   with:
    #     path: ~/.maven-
    #     key: ${{ runner.os }}-maven-${{ hashfiles(arg) }}
    #   uses: actions/cache@version
    #   uses: actions/checkout@version
    # - name: set up jdk 1.8
    #   run: bash <(curl -s https://codecov.io/bash)

# macos:
#   jdk: openjdk8

