name: Manually Migrated Github Actions Workflow

on:
  push:
    branches:
      - v5-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '8'
    
    - name: maven building
      run: MAVEN_OPTS="-Xmx4g" mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    - name: timezone setting
      run: echo "TZ=Asia/Shanghai" >> $GITHUB_ENV

    - name: Report generation in Cobertura
      run: mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip=true
