name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [openjdk8]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

